

dic_of_EFT_operators = {"ctG"       : r"$C_{tG}$",
                        "ctW"       : r"$C_{tW}$",
                        "ctB"       : r"$C_{tB}$",
                        "ctGRe"     : r"$\Re{\left[C_{tG}\right]}$",
                        "ctWRe"     : r"$\Re{\left[C_{tW}\right]}$",
                        "ctBRe"     : r"$\Re{\left[C_{tB}\right]}$",
                        "ctGIm"     : r"$\Im{\left[C_{tG}\right]}$",
                        "ctWIm"     : r"$\Im{\left[C_{tW}\right]}$",
                        "ctBIm"     : r"$\Im{\left[C_{tB}\right]}$",
                        "cHQ1"      : r"$C_{HQ}^{(1)}$",
                        "cHQ3"      : r"$C_{HQ}^{(3)}$",
                        "cHt"       : r"$C_{Ht}$",
                        "cQj"       : r"$C_{Qq}^{(#1,#2)}}$",
                        "cQQ"       : r"$C_{QQ}^{(#1)}}$",
                        "ctu"       : r"$C_{tu}^{(#1)}}$",
                        "ctd"       : r"$C_{td}^{(#1)}}$",
                        "cQu"       : r"$C_{Qu}^{(#1)}}$",
                        "ctj"       : r"$C_{qt}^{(#1)}}$",
                        "cQt"       : r"$C_{Qt}^{(#1)}}$",
                        "cQd"       : r"$C_{Qd}^{(#1)}}$",
                        "cQl"       : r"$C_{lQ,#2}^{(#1)}}$",
                        "cte"       : r"$C_{et,#1}}$",
                        "cQe"       : r"$C_{Qe,#1}}$",
                        "ctl"       : r"$C_{lt,#1}}$"}
